FROM node:14

RUN ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone \
	&& mkdir -p /home/nodejs/app \
	&& apt-get update -y \
    && apt-get install -y node-gyp make gcc git bluetooth bluez libbluetooth-dev libudev-dev libcap2-bin \
	&& rm -rf /var/cache/apk/*

WORKDIR /home/nodejs/app

COPY package*.json ./

RUN setcap cap_net_raw+eip $(eval readlink -f `which node`)

COPY --chown=node:node . .

USER node

ENTRYPOINT ["/bin/bash"]

EXPOSE 3981
