version: '3.5'

services:
  alfred_flowercare_data_collector_service:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: alfred_flowercare_data_collector_service:latest
    container_name: alfred_flowercare_data_collector_service
    restart: always
    hostname: alfred_flowercare_data_collector_service
    network_mode: 'host'
    privileged: true
    ports:
      - '3984:3978'
    command: npm run test

networks:
  alfred:
    name: alfred
    driver: bridge
