FROM node:12

RUN ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone \
	&& apt-get update -y \
	&& apt-get install -yqq \
    && apt-get install -y build-essential usbutils git bluetooth bluez libbluetooth-dev libudev-dev \
	&& mkdir -p /home/nodejs/app

WORKDIR /home/nodejs/app

COPY . /home/nodejs/app

RUN mv certs/alfred_flowercare_data_collector_service-key.pem certs/server.key \
	&& mv certs/alfred_flowercare_data_collector_service.pem certs/server.crt 

RUN npm install nodemon \
	&& npm install

HEALTHCHECK --start-period=60s --interval=10s --timeout=10s --retries=6 CMD ["./healthcheck.sh"]

EXPOSE 3978