name: BUILD_ARM

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 🛠 Build and publish to private registery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        if: success()
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to private registery
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Buildx (build and push image)
        if: success()
        run: docker buildx build --platform linux/arm/v7 --tag ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_flowercare_data_collector_service:arm --output type=image,push=true .
