name: BUILD_ARM

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 🛠 Build and publish to private registery
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: secrets.DOCKER_REGISTERY_URL
      DOCKER_IMAGE: alfred_flowercare_data_collector_service:arm
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
      - name: Checkout repo
        if: success()
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Add private registery to docker deamon
        if: success()
        run: |
          echo "{ \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTERY_URL }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo service docker restart

      - name: Login to private registery
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Buildx (push image)
        if: success()
        run: docker buildx build --platform linux/arm/v7 --tag ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_flowercare_data_collector_service:arm --output type=image,push=true .
